[images]
  remote_images = ["https://same-assets.com/**"]

[build]
  command = "next build || exit 0"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
